#!/usr/bin/env bun
/**
 * Embed Migrations Script
 *
 * Reads migration files from migrations/ directory and generates
 * src/lib/migrations/embedded.ts with all migrations as string constants.
 *
 * Run this before `bun build --compile` to ensure migrations are bundled.
 *
 * Usage: bun run scripts/embed-migrations.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const MIGRATIONS_DIR = join(import.meta.dir, "..", "migrations");
const OUTPUT_FILE = join(
  import.meta.dir,
  "..",
  "src",
  "lib",
  "migrations",
  "embedded.ts"
);

// Regex to parse migration filenames (e.g., "001_add_quick_start.sql")
const MIGRATION_FILE_REGEX = /^(\d{3})_(.+)\.sql$/;

interface ParsedMigration {
  version: number;
  name: string;
  upSql: string;
  downSql: string;
}

/**
 * Parse migration content to extract up/down SQL
 */
function parseMigrationContent(content: string): {
  upSql: string;
  downSql: string;
} {
  const upMarker = /^--\s*UP\s*$/im;
  const downMarker = /^--\s*DOWN\s*$/im;

  const upMatch = content.match(upMarker);
  const downMatch = content.match(downMarker);

  if (!upMatch && !downMatch) {
    return { upSql: content.trim(), downSql: "" };
  }

  if (upMatch && downMatch) {
    const upIndex = upMatch.index! + upMatch[0].length;
    const downIndex = downMatch.index!;

    const upSql = content.slice(upIndex, downIndex).trim();
    const downSql = content.slice(downIndex + downMatch[0].length).trim();

    return { upSql, downSql };
  }

  if (upMatch) {
    const upIndex = upMatch.index! + upMatch[0].length;
    return { upSql: content.slice(upIndex).trim(), downSql: "" };
  }

  return { upSql: content.trim(), downSql: "" };
}

/**
 * Load and parse all migrations
 */
function loadMigrations(): ParsedMigration[] {
  const files = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const migrations: ParsedMigration[] = [];

  for (const file of files) {
    const match = file.match(MIGRATION_FILE_REGEX);
    if (!match) {
      console.warn(`Skipping invalid migration filename: ${file}`);
      continue;
    }

    const version = parseInt(match[1], 10);
    const name = match[2];
    const content = readFileSync(join(MIGRATIONS_DIR, file), "utf-8");
    const { upSql, downSql } = parseMigrationContent(content);

    migrations.push({ version, name, upSql, downSql });
  }

  return migrations;
}

/**
 * Escape backticks and ${} in SQL for template literals
 */
function escapeTemplateLiteral(sql: string): string {
  return sql.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Generate the embedded.ts file content
 */
function generateEmbeddedTs(migrations: ParsedMigration[]): string {
  const migrationEntries = migrations
    .map((m) => {
      return `  {
    version: ${m.version},
    name: "${m.name}",
    upSql: \`${escapeTemplateLiteral(m.upSql)}\`,
    downSql: \`${escapeTemplateLiteral(m.downSql)}\`,
  }`;
    })
    .join(",\n");

  return `/**
 * Embedded Migrations
 *
 * AUTO-GENERATED by scripts/embed-migrations.ts
 * DO NOT EDIT MANUALLY
 *
 * Generated: ${new Date().toISOString()}
 *
 * These migrations are embedded at build time so they work
 * in the compiled binary where import.meta.dir resolves to
 * a virtual path inside the binary.
 */

import type { Migration } from "./types";

/**
 * Embedded migrations for use when filesystem migrations are unavailable
 * (e.g., in compiled binary)
 */
export const EMBEDDED_MIGRATIONS: Migration[] = [
${migrationEntries},
];
`;
}

// Main
const migrations = loadMigrations();
const output = generateEmbeddedTs(migrations);
writeFileSync(OUTPUT_FILE, output);

console.log(`✓ Embedded ${migrations.length} migrations into ${OUTPUT_FILE}`);
