/**
 * Embedded Migrations
 *
 * AUTO-GENERATED by scripts/embed-migrations.ts
 * DO NOT EDIT MANUALLY
 *
 * Generated: 2026-03-24T15:33:02.419Z
 *
 * These migrations are embedded at build time so they work
 * in the compiled binary where import.meta.dir resolves to
 * a virtual path inside the binary.
 */

import type { Migration } from "./types";

/**
 * Embedded migrations for use when filesystem migrations are unavailable
 * (e.g., in compiled binary)
 */
export const EMBEDDED_MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: "add_quick_start",
    upSql: `ALTER TABLE features ADD COLUMN quick_start INTEGER DEFAULT 0;`,
    downSql: `-- Note: SQLite doesn't support DROP COLUMN directly in older versions
-- This is a no-op for safety; manual intervention required for rollback
SELECT 1;`,
  },
  {
    version: 2,
    name: "add_doctorow_verified",
    upSql: `ALTER TABLE features ADD COLUMN doctorow_verified INTEGER DEFAULT 0;
ALTER TABLE features ADD COLUMN doctorow_skips TEXT;`,
    downSql: `SELECT 1;`,
  },
  {
    version: 3,
    name: "add_revision_history",
    upSql: `CREATE TABLE IF NOT EXISTS revision_history (
  id TEXT PRIMARY KEY,
  artifact_path TEXT NOT NULL,
  previous_content TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  reason TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_revision_history_path ON revision_history(artifact_path);
CREATE INDEX IF NOT EXISTS idx_revision_history_timestamp ON revision_history(timestamp);`,
    downSql: `DROP INDEX IF EXISTS idx_revision_history_timestamp;
DROP INDEX IF EXISTS idx_revision_history_path;
DROP TABLE IF EXISTS revision_history;`,
  },
  {
    version: 4,
    name: "add_decomposition_fields",
    upSql: `-- Add rich decomposition fields for batch mode support
-- All columns nullable for backward compatibility with existing features

-- Required fields for batch mode
ALTER TABLE features ADD COLUMN problem_type TEXT;
ALTER TABLE features ADD COLUMN urgency TEXT;
ALTER TABLE features ADD COLUMN primary_user TEXT;
ALTER TABLE features ADD COLUMN integration_scope TEXT;

-- Optional rich fields
ALTER TABLE features ADD COLUMN usage_context TEXT;
ALTER TABLE features ADD COLUMN data_requirements TEXT;
ALTER TABLE features ADD COLUMN performance_requirements TEXT;
ALTER TABLE features ADD COLUMN priority_tradeoff TEXT;

-- Uncertainty handling
ALTER TABLE features ADD COLUMN uncertainties TEXT;
ALTER TABLE features ADD COLUMN clarification_needed TEXT;`,
    downSql: `-- Note: SQLite doesn't support DROP COLUMN directly in older versions
-- This is a no-op for safety; manual intervention required for rollback
SELECT 1;`,
  },
  {
    version: 5,
    name: "add_skip_validation",
    upSql: `-- Add skip validation and audit trail fields
-- Tracks why features were skipped and validates skip decisions

-- Skip audit trail
ALTER TABLE features ADD COLUMN skip_reason TEXT;
ALTER TABLE features ADD COLUMN skip_justification TEXT;
ALTER TABLE features ADD COLUMN skip_validated_at TEXT;
ALTER TABLE features ADD COLUMN skip_duplicate_of TEXT;`,
    downSql: `-- Note: SQLite doesn't support DROP COLUMN directly in older versions
-- This is a no-op for safety; manual intervention required for rollback
SELECT 1;`,
  },
  {
    version: 6,
    name: "add_contrib_prep",
    upSql: `-- Add contrib prep state tracking table
-- Tracks the contribution preparation workflow (inventory → sanitize → extract → verify)

CREATE TABLE IF NOT EXISTS contrib_prep_state (
  feature_id TEXT PRIMARY KEY,
  gate INTEGER NOT NULL DEFAULT 0,
  inventory_included INTEGER DEFAULT 0,
  inventory_excluded INTEGER DEFAULT 0,
  sanitization_pass INTEGER,
  sanitization_findings INTEGER DEFAULT 0,
  tag_name TEXT,
  tag_hash TEXT,
  contrib_branch TEXT,
  verification_pass INTEGER,
  base_branch TEXT DEFAULT 'main',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (feature_id) REFERENCES features(id)
);`,
    downSql: `DROP TABLE IF EXISTS contrib_prep_state;`,
  },
  {
    version: 7,
    name: "lifecycle_extension",
    upSql: `-- Lifecycle extension: harden results, review records, approval gates

CREATE TABLE IF NOT EXISTS harden_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feature_id TEXT NOT NULL,
  test_name TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('pass', 'fail', 'skip', 'pending')),
  evidence TEXT,
  ingested_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (feature_id) REFERENCES features(id)
);

CREATE INDEX IF NOT EXISTS idx_harden_results_feature ON harden_results(feature_id);

CREATE TABLE IF NOT EXISTS review_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feature_id TEXT NOT NULL,
  reviewed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  passed INTEGER NOT NULL DEFAULT 0,
  checks_json TEXT,
  acceptance_json TEXT,
  FOREIGN KEY (feature_id) REFERENCES features(id)
);

CREATE INDEX IF NOT EXISTS idx_review_records_feature ON review_records(feature_id);

CREATE TABLE IF NOT EXISTS approval_gates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feature_id TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
  triggered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME,
  rejection_reason TEXT,
  FOREIGN KEY (feature_id) REFERENCES features(id)
);

CREATE INDEX IF NOT EXISTS idx_approval_gates_feature ON approval_gates(feature_id);`,
    downSql: `DROP TABLE IF EXISTS approval_gates;
DROP TABLE IF EXISTS review_records;
DROP TABLE IF EXISTS harden_results;`,
  },
];
